name: Deployment

on:
  push:
    tags:
      - 'v*'

jobs:
  Build:
    outputs:
      created: ${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 20
      - run: echo "VER=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      - run: npm ci
      - run: npm test
      - run: npm run build
      - run: |
          echo https://github.com/$GITHUB_REPOSITORY/tree/$VER > dist/SOURCE_URL.txt
          npm run version
      - id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.VER }}
          release_name: Release ${{ env.VER }}
          draft: false
          prerelease: false
      - name: Build project
        run: |
          (cd dist && zip -r ../twitch-pasta-saver-${{ env.VER }}.zip *)
      - name: Upload Release Asset
        id: upload_release_asset
        uses: actions/upload-release-asset@v1
        env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
         upload_url: ${{ steps.create_release.outputs.upload_url }}
         asset_path: ./twitch-pasta-saver-${{ env.VER }}.zip
         asset_name: twitch-pasta-saver-${{ env.VER }}.zip
         asset_content_type: application/zip
      - uses: actions/upload-artifact@v2
        with:
          path: dist

  Chrome:
    needs: Build
    if: github.event_name == 'workflow_dispatch' || needs.Build.outputs.created
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
      - run: cd artifact && npx chrome-webstore-upload-cli@1 upload --auto-publish
        env:
          EXTENSION_ID: ${{ secrets.EXTENSION_ID }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}

  Firefox:
    needs: Build
    if: github.event_name == 'workflow_dispatch' || needs.Build.outputs.created
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
      - run: cd artifact && npx web-ext-submit@4
        env:
          WEB_EXT_API_KEY: ${{ secrets.WEB_EXT_API_KEY }}
          WEB_EXT_API_SECRET: ${{ secrets.WEB_EXT_API_SECRET }}
